name: CICD-2

on:
  workflow_dispatch:


jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Build docker conatiner"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "Testing the container"
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying container
        run: echo "Docker compose deploy container"
