name: Deploy to server


on:
    workflow_call:


jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:

            - name: checkout code
              uses: actions/checkout@v4





            - name: SSH to prod server & create app folder
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                 "-----Starting deployment-----"
                 mkdir -p devops


            - name: copy docker compose file
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                source: "."
                target: ~/devops


            - name: SSH to prod server & run the app
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                 "-----Deploying App-----"
                 sudo apt-get update -y
                 sudo apt-get install docker.io docker-compose-v2 -y
                 sudo usermod -aG docker $USER && newgrp docker
                 cd ~/devops && docker compose down && docker compose up -d --build --force-recreate --pull always
